// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.bgfurfeature.coreword.rpc.core_word



object CoreWordProto {
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cg9jb3JlX3dvcmQucHJvdG8SHWNvbS5iZ2Z1cmZlYXR1cmUuY29yZXdvcmQucnBjIjIKBFdvcmQSFgoGbnVtYmVyGAEgASgJU
  gZudW1iZXISEgoEdGV4dBgCIAEoCVIEdGV4dCJHCgxXb3Jkc1JlcXVlc3QSNwoEd29yZBgBIAMoCzIjLmNvbS5iZ2Z1cmZlYXR1c
  mUuY29yZXdvcmQucnBjLldvcmRSBHdvcmQiNAoGUmVzdWx0EhYKBm51bWJlchgBIAEoCVIGbnVtYmVyEhIKBHRleHQYAiADKAlSB
  HRleHQiSwoKV29yZHNSZXBseRI9CgZyZXN1bHQYASADKAsyJS5jb20uYmdmdXJmZWF0dXJlLmNvcmV3b3JkLnJwYy5SZXN1bHRSB
  nJlc3VsdDJ7CglDb3JlV29yZHMSbgoSRXh0cmFjdG9yQ29yZVdvcmRzEisuY29tLmJnZnVyZmVhdHVyZS5jb3Jld29yZC5ycGMuV
  29yZHNSZXF1ZXN0GikuY29tLmJnZnVyZmVhdHVyZS5jb3Jld29yZC5ycGMuV29yZHNSZXBseSIAQgJQAWIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, Seq(
    ))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}