// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.bgfurfeature.coreword.rpc.core_word



@SerialVersionUID(0L)
final case class WordsReply(
    result: _root_.scala.collection.Seq[com.bgfurfeature.coreword.rpc.core_word.Result] = _root_.scala.collection.Seq.empty
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[WordsReply] with com.trueaccord.lenses.Updatable[WordsReply] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      result.foreach(result => __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(result.serializedSize) + result.serializedSize)
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
      result.foreach { __v =>
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__v.serializedSize)
        __v.writeTo(_output__)
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.bgfurfeature.coreword.rpc.core_word.WordsReply = {
      val __result = (_root_.scala.collection.immutable.Vector.newBuilder[com.bgfurfeature.coreword.rpc.core_word.Result] ++= this.result)
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __result += _root_.com.trueaccord.scalapb.LiteParser.readMessage(_input__, com.bgfurfeature.coreword.rpc.core_word.Result.defaultInstance)
          case tag => _input__.skipField(tag)
        }
      }
      com.bgfurfeature.coreword.rpc.core_word.WordsReply(
          result = __result.result()
      )
    }
    def clearResult = copy(result = _root_.scala.collection.Seq.empty)
    def addResult(__vs: com.bgfurfeature.coreword.rpc.core_word.Result*): WordsReply = addAllResult(__vs)
    def addAllResult(__vs: TraversableOnce[com.bgfurfeature.coreword.rpc.core_word.Result]): WordsReply = copy(result = result ++ __vs)
    def withResult(__v: _root_.scala.collection.Seq[com.bgfurfeature.coreword.rpc.core_word.Result]): WordsReply = copy(result = __v)
    def getFieldByNumber(__fieldNumber: Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => result
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(result.map(_.toPMessage)(_root_.scala.collection.breakOut))
      }
    }
    override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.bgfurfeature.coreword.rpc.core_word.WordsReply
}

object WordsReply extends com.trueaccord.scalapb.GeneratedMessageCompanion[com.bgfurfeature.coreword.rpc.core_word.WordsReply] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[com.bgfurfeature.coreword.rpc.core_word.WordsReply] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.bgfurfeature.coreword.rpc.core_word.WordsReply = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    com.bgfurfeature.coreword.rpc.core_word.WordsReply(
      __fieldsMap.getOrElse(__fields.get(0), Nil).asInstanceOf[_root_.scala.collection.Seq[com.bgfurfeature.coreword.rpc.core_word.Result]]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.bgfurfeature.coreword.rpc.core_word.WordsReply] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      com.bgfurfeature.coreword.rpc.core_word.WordsReply(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.collection.Seq[com.bgfurfeature.coreword.rpc.core_word.Result]]).getOrElse(_root_.scala.collection.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = CoreWordProto.javaDescriptor.getMessageTypes.get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = CoreWordProto.scalaDescriptor.messages(3)
  def messageCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = null
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 1 => __out = com.bgfurfeature.coreword.rpc.core_word.Result
    }
    __out
  }
  def enumCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.bgfurfeature.coreword.rpc.core_word.WordsReply(
  )
  implicit class WordsReplyLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, com.bgfurfeature.coreword.rpc.core_word.WordsReply]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, com.bgfurfeature.coreword.rpc.core_word.WordsReply](_l) {
    def result: _root_.com.trueaccord.lenses.Lens[UpperPB, _root_.scala.collection.Seq[com.bgfurfeature.coreword.rpc.core_word.Result]] = field(_.result)((c_, f_) => c_.copy(result = f_))
  }
  final val RESULT_FIELD_NUMBER = 1
}
