// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.bgfurfeature.coreword.rpc.core_word



@SerialVersionUID(0L)
final case class WordsRequest(
    word: _root_.scala.collection.Seq[com.bgfurfeature.coreword.rpc.core_word.Word] = _root_.scala.collection.Seq.empty
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[WordsRequest] with com.trueaccord.lenses.Updatable[WordsRequest] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      word.foreach(word => __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(word.serializedSize) + word.serializedSize)
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
      word.foreach { __v =>
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__v.serializedSize)
        __v.writeTo(_output__)
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.bgfurfeature.coreword.rpc.core_word.WordsRequest = {
      val __word = (_root_.scala.collection.immutable.Vector.newBuilder[com.bgfurfeature.coreword.rpc.core_word.Word] ++= this.word)
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __word += _root_.com.trueaccord.scalapb.LiteParser.readMessage(_input__, com.bgfurfeature.coreword.rpc.core_word.Word.defaultInstance)
          case tag => _input__.skipField(tag)
        }
      }
      com.bgfurfeature.coreword.rpc.core_word.WordsRequest(
          word = __word.result()
      )
    }
    def clearWord = copy(word = _root_.scala.collection.Seq.empty)
    def addWord(__vs: com.bgfurfeature.coreword.rpc.core_word.Word*): WordsRequest = addAllWord(__vs)
    def addAllWord(__vs: TraversableOnce[com.bgfurfeature.coreword.rpc.core_word.Word]): WordsRequest = copy(word = word ++ __vs)
    def withWord(__v: _root_.scala.collection.Seq[com.bgfurfeature.coreword.rpc.core_word.Word]): WordsRequest = copy(word = __v)
    def getFieldByNumber(__fieldNumber: Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => word
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(word.map(_.toPMessage)(_root_.scala.collection.breakOut))
      }
    }
    override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.bgfurfeature.coreword.rpc.core_word.WordsRequest
}

object WordsRequest extends com.trueaccord.scalapb.GeneratedMessageCompanion[com.bgfurfeature.coreword.rpc.core_word.WordsRequest] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[com.bgfurfeature.coreword.rpc.core_word.WordsRequest] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.bgfurfeature.coreword.rpc.core_word.WordsRequest = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    com.bgfurfeature.coreword.rpc.core_word.WordsRequest(
      __fieldsMap.getOrElse(__fields.get(0), Nil).asInstanceOf[_root_.scala.collection.Seq[com.bgfurfeature.coreword.rpc.core_word.Word]]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.bgfurfeature.coreword.rpc.core_word.WordsRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      com.bgfurfeature.coreword.rpc.core_word.WordsRequest(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.collection.Seq[com.bgfurfeature.coreword.rpc.core_word.Word]]).getOrElse(_root_.scala.collection.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = CoreWordProto.javaDescriptor.getMessageTypes.get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = CoreWordProto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = null
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 1 => __out = com.bgfurfeature.coreword.rpc.core_word.Word
    }
    __out
  }
  def enumCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.bgfurfeature.coreword.rpc.core_word.WordsRequest(
  )
  implicit class WordsRequestLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, com.bgfurfeature.coreword.rpc.core_word.WordsRequest]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, com.bgfurfeature.coreword.rpc.core_word.WordsRequest](_l) {
    def word: _root_.com.trueaccord.lenses.Lens[UpperPB, _root_.scala.collection.Seq[com.bgfurfeature.coreword.rpc.core_word.Word]] = field(_.word)((c_, f_) => c_.copy(word = f_))
  }
  final val WORD_FIELD_NUMBER = 1
}
