// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: major.proto

package com.inmind.idmg.major.rpc;

public interface MajorReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.inmind.idmg.major.rpc.MajorReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string major_rep = 1;</code>
   */
  java.lang.String getMajorRep();
  /**
   * <code>optional string major_rep = 1;</code>
   */
  com.google.protobuf.ByteString
      getMajorRepBytes();
}
