// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: major.proto

package com.inmind.idmg.major.rpc;

/**
 * Protobuf type {@code com.inmind.idmg.major.rpc.MajorRequest}
 */
public  final class MajorRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.inmind.idmg.major.rpc.MajorRequest)
    MajorRequestOrBuilder {
  // Use MajorRequest.newBuilder() to construct.
  private MajorRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MajorRequest() {
    majorReq_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MajorRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            majorReq_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.inmind.idmg.major.rpc.Major.internal_static_com_inmind_idmg_major_rpc_MajorRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.inmind.idmg.major.rpc.Major.internal_static_com_inmind_idmg_major_rpc_MajorRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.inmind.idmg.major.rpc.MajorRequest.class, com.inmind.idmg.major.rpc.MajorRequest.Builder.class);
  }

  public static final int MAJOR_REQ_FIELD_NUMBER = 1;
  private volatile java.lang.Object majorReq_;
  /**
   * <code>optional string major_req = 1;</code>
   */
  public java.lang.String getMajorReq() {
    java.lang.Object ref = majorReq_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      majorReq_ = s;
      return s;
    }
  }
  /**
   * <code>optional string major_req = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMajorReqBytes() {
    java.lang.Object ref = majorReq_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      majorReq_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMajorReqBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, majorReq_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMajorReqBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, majorReq_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.inmind.idmg.major.rpc.MajorRequest)) {
      return super.equals(obj);
    }
    com.inmind.idmg.major.rpc.MajorRequest other = (com.inmind.idmg.major.rpc.MajorRequest) obj;

    boolean result = true;
    result = result && getMajorReq()
        .equals(other.getMajorReq());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + MAJOR_REQ_FIELD_NUMBER;
    hash = (53 * hash) + getMajorReq().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.inmind.idmg.major.rpc.MajorRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.inmind.idmg.major.rpc.MajorRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.inmind.idmg.major.rpc.MajorRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.inmind.idmg.major.rpc.MajorRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.inmind.idmg.major.rpc.MajorRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.inmind.idmg.major.rpc.MajorRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.inmind.idmg.major.rpc.MajorRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.inmind.idmg.major.rpc.MajorRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.inmind.idmg.major.rpc.MajorRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.inmind.idmg.major.rpc.MajorRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.inmind.idmg.major.rpc.MajorRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.inmind.idmg.major.rpc.MajorRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.inmind.idmg.major.rpc.MajorRequest)
      com.inmind.idmg.major.rpc.MajorRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inmind.idmg.major.rpc.Major.internal_static_com_inmind_idmg_major_rpc_MajorRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inmind.idmg.major.rpc.Major.internal_static_com_inmind_idmg_major_rpc_MajorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inmind.idmg.major.rpc.MajorRequest.class, com.inmind.idmg.major.rpc.MajorRequest.Builder.class);
    }

    // Construct using com.inmind.idmg.major.rpc.MajorRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      majorReq_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.inmind.idmg.major.rpc.Major.internal_static_com_inmind_idmg_major_rpc_MajorRequest_descriptor;
    }

    public com.inmind.idmg.major.rpc.MajorRequest getDefaultInstanceForType() {
      return com.inmind.idmg.major.rpc.MajorRequest.getDefaultInstance();
    }

    public com.inmind.idmg.major.rpc.MajorRequest build() {
      com.inmind.idmg.major.rpc.MajorRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.inmind.idmg.major.rpc.MajorRequest buildPartial() {
      com.inmind.idmg.major.rpc.MajorRequest result = new com.inmind.idmg.major.rpc.MajorRequest(this);
      result.majorReq_ = majorReq_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.inmind.idmg.major.rpc.MajorRequest) {
        return mergeFrom((com.inmind.idmg.major.rpc.MajorRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.inmind.idmg.major.rpc.MajorRequest other) {
      if (other == com.inmind.idmg.major.rpc.MajorRequest.getDefaultInstance()) return this;
      if (!other.getMajorReq().isEmpty()) {
        majorReq_ = other.majorReq_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.inmind.idmg.major.rpc.MajorRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.inmind.idmg.major.rpc.MajorRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object majorReq_ = "";
    /**
     * <code>optional string major_req = 1;</code>
     */
    public java.lang.String getMajorReq() {
      java.lang.Object ref = majorReq_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        majorReq_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string major_req = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMajorReqBytes() {
      java.lang.Object ref = majorReq_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        majorReq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string major_req = 1;</code>
     */
    public Builder setMajorReq(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      majorReq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string major_req = 1;</code>
     */
    public Builder clearMajorReq() {
      
      majorReq_ = getDefaultInstance().getMajorReq();
      onChanged();
      return this;
    }
    /**
     * <code>optional string major_req = 1;</code>
     */
    public Builder setMajorReqBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      majorReq_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.inmind.idmg.major.rpc.MajorRequest)
  }

  // @@protoc_insertion_point(class_scope:com.inmind.idmg.major.rpc.MajorRequest)
  private static final com.inmind.idmg.major.rpc.MajorRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.inmind.idmg.major.rpc.MajorRequest();
  }

  public static com.inmind.idmg.major.rpc.MajorRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MajorRequest>
      PARSER = new com.google.protobuf.AbstractParser<MajorRequest>() {
    public MajorRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MajorRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MajorRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MajorRequest> getParserForType() {
    return PARSER;
  }

  public com.inmind.idmg.major.rpc.MajorRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

