// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: major.proto

package com.inmind.idmg.major.rpc;

public interface MajorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.inmind.idmg.major.rpc.MajorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string major_req = 1;</code>
   */
  java.lang.String getMajorReq();
  /**
   * <code>optional string major_req = 1;</code>
   */
  com.google.protobuf.ByteString
      getMajorReqBytes();
}
