// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: major.proto

package com.inmind.idmg.major.rpc;

public final class Major {
  private Major() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_inmind_idmg_major_rpc_MajorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_inmind_idmg_major_rpc_MajorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_inmind_idmg_major_rpc_MajorReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_inmind_idmg_major_rpc_MajorReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013major.proto\022\031com.inmind.idmg.major.rpc" +
      "\"!\n\014MajorRequest\022\021\n\tmajor_req\030\001 \001(\t\"\037\n\nM" +
      "ajorReply\022\021\n\tmajor_rep\030\001 \001(\t2q\n\022ResumeMa" +
      "jorService\022[\n\007doMajor\022\'.com.inmind.idmg." +
      "major.rpc.MajorRequest\032%.com.inmind.idmg" +
      ".major.rpc.MajorReply\"\000B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_inmind_idmg_major_rpc_MajorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_inmind_idmg_major_rpc_MajorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_inmind_idmg_major_rpc_MajorRequest_descriptor,
        new java.lang.String[] { "MajorReq", });
    internal_static_com_inmind_idmg_major_rpc_MajorReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_inmind_idmg_major_rpc_MajorReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_inmind_idmg_major_rpc_MajorReply_descriptor,
        new java.lang.String[] { "MajorRep", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
