// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: school_normalize.proto

package com.inmind.idmg.schoolnormalize.rpc;

/**
 * Protobuf type {@code com.inmind.idmg.schoolnormalize.rpc.NormalizeReply}
 */
public  final class NormalizeReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.inmind.idmg.schoolnormalize.rpc.NormalizeReply)
    NormalizeReplyOrBuilder {
  // Use NormalizeReply.newBuilder() to construct.
  private NormalizeReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NormalizeReply() {
    suggest_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private NormalizeReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              suggest_ = new java.util.ArrayList<com.inmind.idmg.schoolnormalize.rpc.NormalSuggest>();
              mutable_bitField0_ |= 0x00000001;
            }
            suggest_.add(
                input.readMessage(com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        suggest_ = java.util.Collections.unmodifiableList(suggest_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.inmind.idmg.schoolnormalize.rpc.SchoolNormalize.internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.inmind.idmg.schoolnormalize.rpc.SchoolNormalize.internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.inmind.idmg.schoolnormalize.rpc.NormalizeReply.class, com.inmind.idmg.schoolnormalize.rpc.NormalizeReply.Builder.class);
  }

  public static final int SUGGEST_FIELD_NUMBER = 1;
  private java.util.List<com.inmind.idmg.schoolnormalize.rpc.NormalSuggest> suggest_;
  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
   */
  public java.util.List<com.inmind.idmg.schoolnormalize.rpc.NormalSuggest> getSuggestList() {
    return suggest_;
  }
  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
   */
  public java.util.List<? extends com.inmind.idmg.schoolnormalize.rpc.NormalSuggestOrBuilder> 
      getSuggestOrBuilderList() {
    return suggest_;
  }
  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
   */
  public int getSuggestCount() {
    return suggest_.size();
  }
  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
   */
  public com.inmind.idmg.schoolnormalize.rpc.NormalSuggest getSuggest(int index) {
    return suggest_.get(index);
  }
  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
   */
  public com.inmind.idmg.schoolnormalize.rpc.NormalSuggestOrBuilder getSuggestOrBuilder(
      int index) {
    return suggest_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < suggest_.size(); i++) {
      output.writeMessage(1, suggest_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < suggest_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, suggest_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.inmind.idmg.schoolnormalize.rpc.NormalizeReply)) {
      return super.equals(obj);
    }
    com.inmind.idmg.schoolnormalize.rpc.NormalizeReply other = (com.inmind.idmg.schoolnormalize.rpc.NormalizeReply) obj;

    boolean result = true;
    result = result && getSuggestList()
        .equals(other.getSuggestList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getSuggestCount() > 0) {
      hash = (37 * hash) + SUGGEST_FIELD_NUMBER;
      hash = (53 * hash) + getSuggestList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.inmind.idmg.schoolnormalize.rpc.NormalizeReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalizeReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalizeReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalizeReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalizeReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalizeReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalizeReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalizeReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalizeReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalizeReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.inmind.idmg.schoolnormalize.rpc.NormalizeReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.inmind.idmg.schoolnormalize.rpc.NormalizeReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.inmind.idmg.schoolnormalize.rpc.NormalizeReply)
      com.inmind.idmg.schoolnormalize.rpc.NormalizeReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inmind.idmg.schoolnormalize.rpc.SchoolNormalize.internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inmind.idmg.schoolnormalize.rpc.SchoolNormalize.internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inmind.idmg.schoolnormalize.rpc.NormalizeReply.class, com.inmind.idmg.schoolnormalize.rpc.NormalizeReply.Builder.class);
    }

    // Construct using com.inmind.idmg.schoolnormalize.rpc.NormalizeReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSuggestFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (suggestBuilder_ == null) {
        suggest_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        suggestBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.inmind.idmg.schoolnormalize.rpc.SchoolNormalize.internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeReply_descriptor;
    }

    public com.inmind.idmg.schoolnormalize.rpc.NormalizeReply getDefaultInstanceForType() {
      return com.inmind.idmg.schoolnormalize.rpc.NormalizeReply.getDefaultInstance();
    }

    public com.inmind.idmg.schoolnormalize.rpc.NormalizeReply build() {
      com.inmind.idmg.schoolnormalize.rpc.NormalizeReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.inmind.idmg.schoolnormalize.rpc.NormalizeReply buildPartial() {
      com.inmind.idmg.schoolnormalize.rpc.NormalizeReply result = new com.inmind.idmg.schoolnormalize.rpc.NormalizeReply(this);
      int from_bitField0_ = bitField0_;
      if (suggestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          suggest_ = java.util.Collections.unmodifiableList(suggest_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.suggest_ = suggest_;
      } else {
        result.suggest_ = suggestBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.inmind.idmg.schoolnormalize.rpc.NormalizeReply) {
        return mergeFrom((com.inmind.idmg.schoolnormalize.rpc.NormalizeReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.inmind.idmg.schoolnormalize.rpc.NormalizeReply other) {
      if (other == com.inmind.idmg.schoolnormalize.rpc.NormalizeReply.getDefaultInstance()) return this;
      if (suggestBuilder_ == null) {
        if (!other.suggest_.isEmpty()) {
          if (suggest_.isEmpty()) {
            suggest_ = other.suggest_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSuggestIsMutable();
            suggest_.addAll(other.suggest_);
          }
          onChanged();
        }
      } else {
        if (!other.suggest_.isEmpty()) {
          if (suggestBuilder_.isEmpty()) {
            suggestBuilder_.dispose();
            suggestBuilder_ = null;
            suggest_ = other.suggest_;
            bitField0_ = (bitField0_ & ~0x00000001);
            suggestBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSuggestFieldBuilder() : null;
          } else {
            suggestBuilder_.addAllMessages(other.suggest_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.inmind.idmg.schoolnormalize.rpc.NormalizeReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.inmind.idmg.schoolnormalize.rpc.NormalizeReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.inmind.idmg.schoolnormalize.rpc.NormalSuggest> suggest_ =
      java.util.Collections.emptyList();
    private void ensureSuggestIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        suggest_ = new java.util.ArrayList<com.inmind.idmg.schoolnormalize.rpc.NormalSuggest>(suggest_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.inmind.idmg.schoolnormalize.rpc.NormalSuggest, com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.Builder, com.inmind.idmg.schoolnormalize.rpc.NormalSuggestOrBuilder> suggestBuilder_;

    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public java.util.List<com.inmind.idmg.schoolnormalize.rpc.NormalSuggest> getSuggestList() {
      if (suggestBuilder_ == null) {
        return java.util.Collections.unmodifiableList(suggest_);
      } else {
        return suggestBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public int getSuggestCount() {
      if (suggestBuilder_ == null) {
        return suggest_.size();
      } else {
        return suggestBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public com.inmind.idmg.schoolnormalize.rpc.NormalSuggest getSuggest(int index) {
      if (suggestBuilder_ == null) {
        return suggest_.get(index);
      } else {
        return suggestBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public Builder setSuggest(
        int index, com.inmind.idmg.schoolnormalize.rpc.NormalSuggest value) {
      if (suggestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuggestIsMutable();
        suggest_.set(index, value);
        onChanged();
      } else {
        suggestBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public Builder setSuggest(
        int index, com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.Builder builderForValue) {
      if (suggestBuilder_ == null) {
        ensureSuggestIsMutable();
        suggest_.set(index, builderForValue.build());
        onChanged();
      } else {
        suggestBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public Builder addSuggest(com.inmind.idmg.schoolnormalize.rpc.NormalSuggest value) {
      if (suggestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuggestIsMutable();
        suggest_.add(value);
        onChanged();
      } else {
        suggestBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public Builder addSuggest(
        int index, com.inmind.idmg.schoolnormalize.rpc.NormalSuggest value) {
      if (suggestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuggestIsMutable();
        suggest_.add(index, value);
        onChanged();
      } else {
        suggestBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public Builder addSuggest(
        com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.Builder builderForValue) {
      if (suggestBuilder_ == null) {
        ensureSuggestIsMutable();
        suggest_.add(builderForValue.build());
        onChanged();
      } else {
        suggestBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public Builder addSuggest(
        int index, com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.Builder builderForValue) {
      if (suggestBuilder_ == null) {
        ensureSuggestIsMutable();
        suggest_.add(index, builderForValue.build());
        onChanged();
      } else {
        suggestBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public Builder addAllSuggest(
        java.lang.Iterable<? extends com.inmind.idmg.schoolnormalize.rpc.NormalSuggest> values) {
      if (suggestBuilder_ == null) {
        ensureSuggestIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, suggest_);
        onChanged();
      } else {
        suggestBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public Builder clearSuggest() {
      if (suggestBuilder_ == null) {
        suggest_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        suggestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public Builder removeSuggest(int index) {
      if (suggestBuilder_ == null) {
        ensureSuggestIsMutable();
        suggest_.remove(index);
        onChanged();
      } else {
        suggestBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.Builder getSuggestBuilder(
        int index) {
      return getSuggestFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public com.inmind.idmg.schoolnormalize.rpc.NormalSuggestOrBuilder getSuggestOrBuilder(
        int index) {
      if (suggestBuilder_ == null) {
        return suggest_.get(index);  } else {
        return suggestBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public java.util.List<? extends com.inmind.idmg.schoolnormalize.rpc.NormalSuggestOrBuilder> 
         getSuggestOrBuilderList() {
      if (suggestBuilder_ != null) {
        return suggestBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(suggest_);
      }
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.Builder addSuggestBuilder() {
      return getSuggestFieldBuilder().addBuilder(
          com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.getDefaultInstance());
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.Builder addSuggestBuilder(
        int index) {
      return getSuggestFieldBuilder().addBuilder(
          index, com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.getDefaultInstance());
    }
    /**
     * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
     */
    public java.util.List<com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.Builder> 
         getSuggestBuilderList() {
      return getSuggestFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.inmind.idmg.schoolnormalize.rpc.NormalSuggest, com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.Builder, com.inmind.idmg.schoolnormalize.rpc.NormalSuggestOrBuilder> 
        getSuggestFieldBuilder() {
      if (suggestBuilder_ == null) {
        suggestBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.inmind.idmg.schoolnormalize.rpc.NormalSuggest, com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.Builder, com.inmind.idmg.schoolnormalize.rpc.NormalSuggestOrBuilder>(
                suggest_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        suggest_ = null;
      }
      return suggestBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.inmind.idmg.schoolnormalize.rpc.NormalizeReply)
  }

  // @@protoc_insertion_point(class_scope:com.inmind.idmg.schoolnormalize.rpc.NormalizeReply)
  private static final com.inmind.idmg.schoolnormalize.rpc.NormalizeReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.inmind.idmg.schoolnormalize.rpc.NormalizeReply();
  }

  public static com.inmind.idmg.schoolnormalize.rpc.NormalizeReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NormalizeReply>
      PARSER = new com.google.protobuf.AbstractParser<NormalizeReply>() {
    public NormalizeReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new NormalizeReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NormalizeReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NormalizeReply> getParserForType() {
    return PARSER;
  }

  public com.inmind.idmg.schoolnormalize.rpc.NormalizeReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

