// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: school_normalize.proto

package com.inmind.idmg.schoolnormalize.rpc;

public interface NormalizeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.inmind.idmg.schoolnormalize.rpc.NormalizeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalFeature features = 1;</code>
   */
  java.util.List<com.inmind.idmg.schoolnormalize.rpc.NormalFeature> 
      getFeaturesList();
  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalFeature features = 1;</code>
   */
  com.inmind.idmg.schoolnormalize.rpc.NormalFeature getFeatures(int index);
  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalFeature features = 1;</code>
   */
  int getFeaturesCount();
  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalFeature features = 1;</code>
   */
  java.util.List<? extends com.inmind.idmg.schoolnormalize.rpc.NormalFeatureOrBuilder> 
      getFeaturesOrBuilderList();
  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalFeature features = 1;</code>
   */
  com.inmind.idmg.schoolnormalize.rpc.NormalFeatureOrBuilder getFeaturesOrBuilder(
      int index);
}
