// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: school_normalize.proto

package com.inmind.idmg.schoolnormalize.rpc;

public interface NormalFeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.inmind.idmg.schoolnormalize.rpc.NormalFeature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>optional string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>optional string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
