// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: school_normalize.proto

package com.inmind.idmg.schoolnormalize.rpc;

public interface NormalSuggestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.inmind.idmg.schoolnormalize.rpc.NormalSuggest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string text = 1;</code>
   */
  java.util.List<java.lang.String>
      getTextList();
  /**
   * <code>repeated string text = 1;</code>
   */
  int getTextCount();
  /**
   * <code>repeated string text = 1;</code>
   */
  java.lang.String getText(int index);
  /**
   * <code>repeated string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes(int index);

  /**
   * <code>optional string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional .com.inmind.idmg.schoolnormalize.rpc.Status status = 3;</code>
   */
  int getStatusValue();
  /**
   * <code>optional .com.inmind.idmg.schoolnormalize.rpc.Status status = 3;</code>
   */
  com.inmind.idmg.schoolnormalize.rpc.Status getStatus();
}
