// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: school_normalize.proto

package com.inmind.idmg.schoolnormalize.rpc;

/**
 * Protobuf type {@code com.inmind.idmg.schoolnormalize.rpc.NormalSuggest}
 */
public  final class NormalSuggest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.inmind.idmg.schoolnormalize.rpc.NormalSuggest)
    NormalSuggestOrBuilder {
  // Use NormalSuggest.newBuilder() to construct.
  private NormalSuggest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NormalSuggest() {
    text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    id_ = "";
    status_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private NormalSuggest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              text_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            text_.add(s);
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        text_ = text_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.inmind.idmg.schoolnormalize.rpc.SchoolNormalize.internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalSuggest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.inmind.idmg.schoolnormalize.rpc.SchoolNormalize.internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalSuggest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.class, com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.Builder.class);
  }

  private int bitField0_;
  public static final int TEXT_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList text_;
  /**
   * <code>repeated string text = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getTextList() {
    return text_;
  }
  /**
   * <code>repeated string text = 1;</code>
   */
  public int getTextCount() {
    return text_.size();
  }
  /**
   * <code>repeated string text = 1;</code>
   */
  public java.lang.String getText(int index) {
    return text_.get(index);
  }
  /**
   * <code>repeated string text = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTextBytes(int index) {
    return text_.getByteString(index);
  }

  public static final int ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object id_;
  /**
   * <code>optional string id = 2;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>optional string id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_;
  /**
   * <code>optional .com.inmind.idmg.schoolnormalize.rpc.Status status = 3;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>optional .com.inmind.idmg.schoolnormalize.rpc.Status status = 3;</code>
   */
  public com.inmind.idmg.schoolnormalize.rpc.Status getStatus() {
    com.inmind.idmg.schoolnormalize.rpc.Status result = com.inmind.idmg.schoolnormalize.rpc.Status.valueOf(status_);
    return result == null ? com.inmind.idmg.schoolnormalize.rpc.Status.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < text_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_.getRaw(i));
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
    }
    if (status_ != com.inmind.idmg.schoolnormalize.rpc.Status.NORMALIZE_FAILED.getNumber()) {
      output.writeEnum(3, status_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < text_.size(); i++) {
        dataSize += computeStringSizeNoTag(text_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTextList().size();
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
    }
    if (status_ != com.inmind.idmg.schoolnormalize.rpc.Status.NORMALIZE_FAILED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, status_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.inmind.idmg.schoolnormalize.rpc.NormalSuggest)) {
      return super.equals(obj);
    }
    com.inmind.idmg.schoolnormalize.rpc.NormalSuggest other = (com.inmind.idmg.schoolnormalize.rpc.NormalSuggest) obj;

    boolean result = true;
    result = result && getTextList()
        .equals(other.getTextList());
    result = result && getId()
        .equals(other.getId());
    result = result && status_ == other.status_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getTextCount() > 0) {
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getTextList().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.inmind.idmg.schoolnormalize.rpc.NormalSuggest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalSuggest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalSuggest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalSuggest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalSuggest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalSuggest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalSuggest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalSuggest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalSuggest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.inmind.idmg.schoolnormalize.rpc.NormalSuggest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.inmind.idmg.schoolnormalize.rpc.NormalSuggest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.inmind.idmg.schoolnormalize.rpc.NormalSuggest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.inmind.idmg.schoolnormalize.rpc.NormalSuggest)
      com.inmind.idmg.schoolnormalize.rpc.NormalSuggestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.inmind.idmg.schoolnormalize.rpc.SchoolNormalize.internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalSuggest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.inmind.idmg.schoolnormalize.rpc.SchoolNormalize.internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalSuggest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.class, com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.Builder.class);
    }

    // Construct using com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = "";

      status_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.inmind.idmg.schoolnormalize.rpc.SchoolNormalize.internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalSuggest_descriptor;
    }

    public com.inmind.idmg.schoolnormalize.rpc.NormalSuggest getDefaultInstanceForType() {
      return com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.getDefaultInstance();
    }

    public com.inmind.idmg.schoolnormalize.rpc.NormalSuggest build() {
      com.inmind.idmg.schoolnormalize.rpc.NormalSuggest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.inmind.idmg.schoolnormalize.rpc.NormalSuggest buildPartial() {
      com.inmind.idmg.schoolnormalize.rpc.NormalSuggest result = new com.inmind.idmg.schoolnormalize.rpc.NormalSuggest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        text_ = text_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.text_ = text_;
      result.id_ = id_;
      result.status_ = status_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.inmind.idmg.schoolnormalize.rpc.NormalSuggest) {
        return mergeFrom((com.inmind.idmg.schoolnormalize.rpc.NormalSuggest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.inmind.idmg.schoolnormalize.rpc.NormalSuggest other) {
      if (other == com.inmind.idmg.schoolnormalize.rpc.NormalSuggest.getDefaultInstance()) return this;
      if (!other.text_.isEmpty()) {
        if (text_.isEmpty()) {
          text_ = other.text_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTextIsMutable();
          text_.addAll(other.text_);
        }
        onChanged();
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.inmind.idmg.schoolnormalize.rpc.NormalSuggest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.inmind.idmg.schoolnormalize.rpc.NormalSuggest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTextIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        text_ = new com.google.protobuf.LazyStringArrayList(text_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTextList() {
      return text_.getUnmodifiableView();
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public int getTextCount() {
      return text_.size();
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public java.lang.String getText(int index) {
      return text_.get(index);
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes(int index) {
      return text_.getByteString(index);
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public Builder setText(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTextIsMutable();
      text_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public Builder addText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTextIsMutable();
      text_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public Builder addAllText(
        java.lang.Iterable<java.lang.String> values) {
      ensureTextIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, text_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public Builder clearText() {
      text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public Builder addTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTextIsMutable();
      text_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>optional string id = 2;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string id = 2;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string id = 2;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string id = 2;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>optional .com.inmind.idmg.schoolnormalize.rpc.Status status = 3;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .com.inmind.idmg.schoolnormalize.rpc.Status status = 3;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.inmind.idmg.schoolnormalize.rpc.Status status = 3;</code>
     */
    public com.inmind.idmg.schoolnormalize.rpc.Status getStatus() {
      com.inmind.idmg.schoolnormalize.rpc.Status result = com.inmind.idmg.schoolnormalize.rpc.Status.valueOf(status_);
      return result == null ? com.inmind.idmg.schoolnormalize.rpc.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.inmind.idmg.schoolnormalize.rpc.Status status = 3;</code>
     */
    public Builder setStatus(com.inmind.idmg.schoolnormalize.rpc.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.inmind.idmg.schoolnormalize.rpc.Status status = 3;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.inmind.idmg.schoolnormalize.rpc.NormalSuggest)
  }

  // @@protoc_insertion_point(class_scope:com.inmind.idmg.schoolnormalize.rpc.NormalSuggest)
  private static final com.inmind.idmg.schoolnormalize.rpc.NormalSuggest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.inmind.idmg.schoolnormalize.rpc.NormalSuggest();
  }

  public static com.inmind.idmg.schoolnormalize.rpc.NormalSuggest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NormalSuggest>
      PARSER = new com.google.protobuf.AbstractParser<NormalSuggest>() {
    public NormalSuggest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new NormalSuggest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NormalSuggest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NormalSuggest> getParserForType() {
    return PARSER;
  }

  public com.inmind.idmg.schoolnormalize.rpc.NormalSuggest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

