// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: school_normalize.proto

package com.inmind.idmg.schoolnormalize.rpc;

public interface NormalizeReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.inmind.idmg.schoolnormalize.rpc.NormalizeReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
   */
  java.util.List<com.inmind.idmg.schoolnormalize.rpc.NormalSuggest> 
      getSuggestList();
  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
   */
  com.inmind.idmg.schoolnormalize.rpc.NormalSuggest getSuggest(int index);
  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
   */
  int getSuggestCount();
  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
   */
  java.util.List<? extends com.inmind.idmg.schoolnormalize.rpc.NormalSuggestOrBuilder> 
      getSuggestOrBuilderList();
  /**
   * <code>repeated .com.inmind.idmg.schoolnormalize.rpc.NormalSuggest suggest = 1;</code>
   */
  com.inmind.idmg.schoolnormalize.rpc.NormalSuggestOrBuilder getSuggestOrBuilder(
      int index);
}
