// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: school_normalize.proto

package com.inmind.idmg.schoolnormalize.rpc;

public final class SchoolNormalize {
  private SchoolNormalize() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalFeature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalFeature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalSuggest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalSuggest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026school_normalize.proto\022#com.inmind.idm" +
      "g.schoolnormalize.rpc\")\n\rNormalFeature\022\014" +
      "\n\004text\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\"X\n\020NormalizeReq" +
      "uest\022D\n\010features\030\001 \003(\01322.com.inmind.idmg" +
      ".schoolnormalize.rpc.NormalFeature\"f\n\rNo" +
      "rmalSuggest\022\014\n\004text\030\001 \003(\t\022\n\n\002id\030\002 \001(\t\022;\n" +
      "\006status\030\003 \001(\0162+.com.inmind.idmg.schoolno" +
      "rmalize.rpc.Status\"U\n\016NormalizeReply\022C\n\007" +
      "suggest\030\001 \003(\01322.com.inmind.idmg.schoolno" +
      "rmalize.rpc.NormalSuggest*5\n\006Status\022\024\n\020N",
      "ORMALIZE_FAILED\020\000\022\025\n\021NORMALIZE_SUCCESS\020\001" +
      "2\225\001\n\026SchoolNormalizeService\022{\n\013doNormali" +
      "ze\0225.com.inmind.idmg.schoolnormalize.rpc" +
      ".NormalizeRequest\0323.com.inmind.idmg.scho" +
      "olnormalize.rpc.NormalizeReply\"\000B\002P\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalFeature_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalFeature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalFeature_descriptor,
        new java.lang.String[] { "Text", "Id", });
    internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeRequest_descriptor,
        new java.lang.String[] { "Features", });
    internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalSuggest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalSuggest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalSuggest_descriptor,
        new java.lang.String[] { "Text", "Id", "Status", });
    internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_inmind_idmg_schoolnormalize_rpc_NormalizeReply_descriptor,
        new java.lang.String[] { "Suggest", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
