// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.bgfurfeature.hello.rpc.hello

object HelloProto {
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CgtoZWxsby5wcm90bxIaY29tLmJnZnVyZmVhdHVyZS5oZWxsby5ycGMiIgoMSGVsbG9SZXF1ZXN0EhIKBG5hbWUYASABKAlSB
  G5hbWUiJgoKSGVsbG9SZXBseRIYCgdtZXNzYWdlGAEgASgJUgdtZXNzYWdlMs4BCgdHcmVldGVyEl4KCFNheUhlbGxvEiguY29tL
  mJnZnVyZmVhdHVyZS5oZWxsby5ycGMuSGVsbG9SZXF1ZXN0GiYuY29tLmJnZnVyZmVhdHVyZS5oZWxsby5ycGMuSGVsbG9SZXBse
  SIAEmMKDVNheUhlbGxvQWdhaW4SKC5jb20uYmdmdXJmZWF0dXJlLmhlbGxvLnJwYy5IZWxsb1JlcXVlc3QaJi5jb20uYmdmdXJmZ
  WF0dXJlLmhlbGxvLnJwYy5IZWxsb1JlcGx5IgBCAlABYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, Seq(
    ))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}